name: ci-checks

on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

jobs:

  ci-checks:
    uses: vipm-io/OpenG-Tookit/.github/workflows/ci-checks.yml@main

  auto-doc:
    uses: vipm-io/OpenG-Tookit/.github/workflows/auto-doc.yml@main
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    secrets: inherit
